-- Drop the lowercase table and recreate with correct case
DROP TABLE IF EXISTS airport_weather_forecast;
CREATE TABLE AIRPORT_WEATHER_FORECAST (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CITY_NAME VARCHAR(50) NOT NULL,
    AIRPORT_NAME VARCHAR(50) NOT NULL,
    START_DATE VARCHAR(10) NOT NULL,
    END_DATE VARCHAR(10) NOT NULL,
    AVERAGE_TEMPERATURE DOUBLE NOT NULL
);

